version: '3.8'

services:
  # Development server
  dev-server:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: npx http-server -p 8080 -c-1
    environment:
      - NODE_ENV=development
    networks:
      - game-network

  # WASM builder service
  wasm-builder:
    image: emscripten/emsdk:latest
    working_dir: /app
    volumes:
      - ./wasm:/app/wasm
      - ./public:/app/public
    command: >
      emcc /app/wasm/game_engine.cpp
      -I/app/wasm/include
      -O3 -s WASM=1 -s MODULARIZE=1
      -s EXPORT_NAME='GameEngine'
      -s ALLOW_MEMORY_GROWTH=1
      -o /app/public/game_engine.js
    networks:
      - game-network

networks:
  game-network:
    driver: bridge