version: '3.8'

services:
  wasm-builder:
    build:
      context: .
      dockerfile: Dockerfile.wasm
    container_name: wasm-game-builder
    volumes:
      - ./wasm:/app/wasm
      - ./public:/app/public
      - ./scripts:/app/scripts
      - ./tests:/app/tests
      - ./.build-cache:/app/.build-cache
    environment:
      - BUILD_MODE=${BUILD_MODE:-release}
    command: ["/app/scripts/wasm-build-helper.sh", "build", "${BUILD_MODE:-release}"]
    
  wasm-watcher:
    build:
      context: .
      dockerfile: Dockerfile.wasm
    container_name: wasm-game-watcher
    volumes:
      - ./wasm:/app/wasm
      - ./public:/app/public
      - ./scripts:/app/scripts
      - ./tests:/app/tests
      - ./.build-cache:/app/.build-cache
    environment:
      - BUILD_MODE=${BUILD_MODE:-release}
    command: ["/app/scripts/wasm-build-helper.sh", "watch", "${BUILD_MODE:-release}"]
    
  wasm-dev-server:
    image: node:18-alpine
    container_name: wasm-game-server
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    command: npx http-server -p 8080 -c-1
    depends_on:
      - wasm-builder