name: Test Matrix

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

# Cancel in-progress runs for PRs
concurrency:
  group: test-${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  # Quick checks that should pass before running expensive tests
  pre-checks:
    runs-on: ubuntu-latest
    outputs:
      should_test: ${{ steps.changes.outputs.should_test }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check for code changes
        id: changes
        run: |
          # Check if only documentation was changed
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD 2>/dev/null || git diff --name-only origin/main...HEAD)
          
          # If only docs/README changed, skip tests
          if echo "$CHANGED_FILES" | grep -vE "^(docs/|.*\.md$|\.github/.*\.md$)" > /dev/null; then
            echo "should_test=true" >> $GITHUB_OUTPUT
          else
            echo "should_test=false" >> $GITHUB_OUTPUT
            echo "::notice::Skipping tests - only documentation changed"
          fi
      
      - name: Lint check
        if: steps.changes.outputs.should_test == 'true'
        run: |
          # Quick lint check
          find . -name "*.js" -not -path "./node_modules/*" -not -path "./emsdk/*" \
            -exec node --check {} \; 2>&1 | tee lint-results.txt || true
          
          if grep -q "SyntaxError" lint-results.txt; then
            echo "::error::Syntax errors found"
            exit 1
          fi

  # Matrix test strategy for parallel execution
  test:
    needs: pre-checks
    if: needs.pre-checks.outputs.should_test == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [16, 18, 20]
        test-suite:
          - unit
          - integration
          - browser
        exclude:
          # Skip browser tests on older Node versions
          - node: 16
            test-suite: browser
    
    name: Test ${{ matrix.test-suite }} - Node ${{ matrix.node }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node${{ matrix.node }}-
      
      - name: Install dependencies
        run: |
          npm ci --prefer-offline --no-audit --no-fund
      
      - name: Run unit tests
        if: matrix.test-suite == 'unit'
        run: |
          echo "::group::Unit Tests"
          npm run test:game || true
          echo "::endgroup::"
      
      - name: Run integration tests
        if: matrix.test-suite == 'integration'
        run: |
          echo "::group::Integration Tests"
          npm run test:wolf || true
          echo "::endgroup::"
      
      - name: Run browser tests
        if: matrix.test-suite == 'browser'
        run: |
          echo "::group::Browser Tests"
          # Install playwright for browser testing
          npx playwright install chromium --with-deps || true
          
          # Run browser-based tests
          node -e "
            const http = require('http');
            const fs = require('fs');
            const path = require('path');
            
            // Simple server for testing
            const server = http.createServer((req, res) => {
              const filePath = path.join(__dirname, req.url === '/' ? 'index.html' : req.url);
              fs.readFile(filePath, (err, data) => {
                if (err) {
                  res.writeHead(404);
                  res.end('Not found');
                } else {
                  res.writeHead(200);
                  res.end(data);
                }
              });
            });
            
            server.listen(8080, () => {
              console.log('Test server running on http://localhost:8080');
              setTimeout(() => server.close(), 30000); // Auto-close after 30s
            });
          " &
          
          # Wait for server
          sleep 2
          
          # Check if pages load without errors
          curl -f http://localhost:8080/game.html > /dev/null 2>&1 || echo "::warning::game.html not accessible"
          
          echo "::endgroup::"
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.os }}-node${{ matrix.node }}-${{ matrix.test-suite }}
          path: |
            test-results/
            coverage/
          retention-days: 7

  # Summary job
  test-summary:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Test Summary
        run: |
          echo "## Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ needs.test.result }}" == "success" ]; then
            echo "✅ All tests passed!" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ needs.test.result }}" == "failure" ]; then
            echo "❌ Some tests failed. Check the logs for details." >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ Tests were skipped or cancelled." >> $GITHUB_STEP_SUMMARY
          fi